Pr nicolen component base class
RevyaS/MockingBoard pull request #6
Opened 2023-06-17 14:34 UTC by razstvien01

PR for the FF:

Toggled in Component List:

1. Added Sample Component Button
2. Mouse Move/Hover: for the Guide Shape of the Component
3. The component always at the front of the layers
4. The component's relative position to the other page fix.

2023-06-23 12:16 UTC, RevyaS commented on App/scripts/index.js
> +        log('Circle button clicked');
Remove comments

2023-06-23 12:20 UTC, RevyaS commented on App/scripts/shapes/Page.js
> +        let log = console.log;
Remove console logs

2023-06-23 12:20 UTC, RevyaS commented on App/scripts/shapes/Page.js
> +        log('MaxZIndex ' + maxZIndex);
Remove comments

2023-06-23 12:20 UTC, RevyaS commented on App/scripts/shapes/Page.js
> +        log(mousePos);
Remove comments

2023-06-23 12:24 UTC, RevyaS requested changes
Added Comments, please resolve

2023-06-30 14:04 UTC, razstvien01 commented on App/scripts/index.js
> +        log('Circle button clicked');
done

2023-06-30 14:04 UTC, razstvien01 commented on App/scripts/shapes/Page.js
> +        log('MaxZIndex ' + maxZIndex);
done

2023-06-30 14:04 UTC, razstvien01 commented on App/scripts/shapes/Page.js
> +        log(mousePos);
done

2023-08-05 11:46 UTC, closed without merging